x-common: &common
  env_file: ./.env
  restart: always
  networks: 
    - sample
  
version: '3'
services:
  sample.api-dev:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/dev.api:2023.09.24.1
    ports:
      - 7001:80
    environment: &sample-api-env
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 1
    <<: *common
  sample.api:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/dev.api:2023.09.24.1
    environment: *sample-api-env
    deploy:
      replicas: 2
      update_config:
        order: start-first
    <<: *common
  iaas-admin-ts:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/iaas-admin-ts:2023.09.24.1
    ports:
      - 8080:80
      - 10443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-www:/usr/share/certbot/www:ro #http验证目录，可设置ro为只读，因为文件最终时通过certbot容器映射来的
      - certbot-ssl:/usr/share/certbot/ssl:ro #证书位置，同上
    environment:
      - NODE_ENV=production
    <<: *common
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #         - certbot-www:/usr/share/certbot/www:rw #http验证目录，可设置rw可写，与nginx容器对应的宿主机目录时一致的
  #         - certbot-ssl:/etc/letsencrypt:rw #证书位置，同上，注意不要只映射到live，而是它的上一级
  #   command: [ "certonly","--webroot","--webroot-path","/usr/share/certbot/www/","-d","admin.galos.top"]
  jaeger:
    image: quay.io/jaegertracing/all-in-one:1.49
    ports:
      # - 6831:6831/udp
      # - 6832:6832/udp
      # - 5778:5778 
      - 16686:16686
      - 4317:4317
      - 4318:4318
      # - 14250:14250
      # - 14268:14268
      # - 14269:14269
      # - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - sample
  nacos-server:
    image: nacos/nacos-server@sha256:38cb6e6244635b7fd287600bc055eba4d970e9e002dc70c40da871ecad7c8fe2
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - db_pool_config_connetionTimeout=60000
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=jY0#R599#%17#&5g^^B!zT$#9g0A0Z
    networks:
      - sample
  mysql: 
    # 指定镜像和版本
    # image: mysql:5.7.35         
    image: mysql:8.0.31            
    ports:
      - "13306:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: jY0#R599#%17#&5g^^B!zT$#9g0A0Z
    volumes:
      # 挂载数据目录
      - nacos-data:/var/lib/mysql
      # 挂载配置文件目录
      - ./config:/etc/mysql/conf.d 
networks:
  sample:
   driver: bridge
volumes:
  nacos-data:
  certbot-ssl:
  certbot-www:
  