version: '3.8'
services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    networks:
      - prom 
networks:
  prom:
    driver: bridge