version: '3.8'
services:
  web-check:
    image: lissy93/web-check
    container_name: web-check
    restart: unless-stopped
    ports:
      - 8230:3000
    networks:
      - web-check
networks:
  web-check:
    driver: bridge