version: '3.8'
services:
  namesrv: 
    image: apache/rocketmq
    command:  ./mqnamesrv
    restart: always
    ports:
      - 9876:9876
    networks:
      - rocketmq
  broker:
    image: apache/rocketmq
    command:  ./mqbroker -n namesrv:9876
    ports:
      - 10911:10911
      - 10909:10909
    volumes:
      - broker-store:/home/rocketmq/store
    networks:
      - rocketmq
  console:
    image: pangliang/rocketmq-console-ng
    ports:
      - 9999:8080
    environment:
      # - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876-Dcom.rocketmq.sendMessageWithVIPChannel=false
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876
    networks:
      - rocketmq
networks:
  rocketmq:
    driver: bridge
volumes:
  broker-store:

