version: '3.8'
services:
  redis:
    # network_mode: 'host'
    image: redis
    ports:
      - 6379:6379
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - ./logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf