version: '3.8'

services:

  mysql-db: 
    # 指定镜像和版本
    image: mysql:8.0                   
    ports:
      - "3306:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: jY0#R599#%17#&5g^^B!zT$#9g0A0Z
    volumes:
      # 挂载数据目录
      - "./data:/var/lib/mysql" 
      # 挂载配置文件目录
      - "./config:/etc/mysql/conf.d"   
