version: '3.8'
services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=^1#uor612X
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090" --address ":9000"
    networks:
      - minio
networks:
  minio:
    driver: bridge
volumes:
  minio-data: